# Generated by Django 5.1.4 on 2024-12-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="tier",
            field=models.CharField(
                choices=[
                    ("KPL", "Kenyan Premier League"),
                    ("NSL", "National Super League"),
                ],
                max_length=50,
            ),
        ),
    ]
