# Generated by Django 5.1.4 on 2024-12-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0002_alter_league_tier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="league",
            name="name",
        ),
    ]
